[project]
name = "sophia-capture"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "opencv-python>=4.11.0.86",
    "pyinstaller>=6.13.0",
    "pyside6>=6.9.0",
]
